### PR TITLE
Version 1.3 release preparation

### PR DESCRIPTION
**Pull request by AlexTate**
Documentation:
- Sequence-based counting and overlap shift parameters have been added in tiny-count.md
- Stage 1 selection description has been cleaned up in tiny-count.md
- The Features Sheet section has been cleaned up in Configuration.md

Workflow:
- New bowtie option: `-m` for providing the drop threshold for reads with too many alignments
- The CWL for bowtie's CommandLineTool and its step in the CWL Workflow now lists its parameters in the same order they occur in bowtie's help string

Run Config:
- Comment lines now indicate the descriptive argument flag that each option corresponds to in the bowtie section

tiny-plot:
- The "%" character has been removed from tick labels in `class_charts` and `rule_charts`

Bug fixes:
- Incorrect or otherwise risky uses of dict.get(key) and dict.get(key, default) have been corrected. False logical paths for these instances are mostly rare (things like users deleting expected keys or changing their type, or features with a Parent= tag that is missing a value), or were otherwise in harmless code sections (empty `run_name` in the Run Config). These bugs would have triggered an exception shortly after so there is no concern about compromised accuracy.
- The PathsFile class now checks to make sure all expected keys are present as a backward compatibility check

### CODE REVIEW

**Comment by AlexTate** [comment]
**More updates:**
- Documentation and config file comments have been updated to specify that the `run_directory` key is actually for the suffix of the final output directory name, and that it is optional. Also adding a small correction to ensure that subdirectory structure is preserved if it is present in `run_directory`
- Updates to Configuration.md:
    - GFF files are optional
    - Workaround solution for experiments with more than one control condition
    - Normalization constants in Samples Sheet can be used for spike-in normalization

**Comment by AlexTate** [comment]
**More updates:**
- The workflow diagram's legend has been modified and the legend of the anchored overlap selector has been corrected
- Broken links in tiny-plot.md have been fixed
- The description of pipeline resume runs has been brought up to date
- Rephrased description of the sequence-based counting mode

**Comment by taimontgomery** [comment]
A couple minor issues:
1. paths.yml, line 26:  no value for run_directory raises exception.
2. run_config.yml, line 20: can we leave user blank?

**Comment by AlexTate** [comment]
> 1. paths.yml, line 26:  no value for run_directory raises exception.

Thanks for catching that, I made those changes too hastily and neglected to test because it seemed so straightforward. I've addressed this bug, wrote some test cases for it, and addressed a couple of other edge cases. Users can provide empty values, empty strings, and integers in `user`, `run_name`, and `run_directory` now.

> 2. run_config.yml, line 20: can we leave user blank?

Addressed in [b8d51be](https://github.com/MontgomeryLab/tinyRNA/pull/284/commits/b8d51be293f19c077d4fc18196eb9a494ce8d7ae)

**Pull request merged**
