### PR TITLE
Counter: additional interval selectors have been added

### LINKED ISSUE #164: Counter: expand options for strict interval matching
The following are valid options for the Match column of the Features Sheet:
- `Partial`: single base overlap for a match
- `Full`: (feature start ≤ alignment interval ≤ feature end) for a match

The following options should be added to this selector:
- `Exact`: (feature start = alignment start; feature end = alignment end) for a match
- `5' anchored`:
    - If same strand: (feature start = alignment start) for a match
    - If opposite strand: (feature start = alignment end) for a match
- `3' anchored`:
    - If same strand: (feature end = alignment end) for a match
    - If opposite strand: (feature end = alignment start) for a match

### PR DESCRIPTION
**Pull request by AlexTate**
Additional interval selectors have been added for `Exact`, ``5' anchored`, and ``3' anchored`.

The names of the `anchored` selectors may lead to some confusion. Positions in GFF3 and SAM files are defined using the same axis and origin regardless of strand. The `start` position does not imply `5' position`. ~~Therefore strand is not considered when determining a match. An alignment matches a `5' anchored` selector when its `start` position matches the feature. The same is true for the `end` position when using a `3' anchored` selector.~~
Turns out I was right: there was certainly room for confusion here (my own). See recent comments below.

Closes #164

### CODE REVIEW

**Comment by AlexTate** [comment]
Interval selectors are now objects which are stored in each identity match tuple of each feature record in the StepVector. Like the other selectors, candidate alignments are evaluated by calling the selector's __contains__() method. This leverages the bytecode advantage of using the `in` operator (COMPARE_OP) rather than an expensive function call (LOAD+CALL_METHOD or LOAD+CALL_FUNCTION).

**Comment by taimontgomery** [comment]
Need to revise it so that 5' and 3' anchor points account for the strand the small RNA is derived from as well as the strand the feature is derived from.

**Comment by AlexTate** [comment]
Strand semantics have been corrected for 3'/5' Anchored selectors
3' and 5' anchored

**Comment by taimontgomery** [comment]
very nice!

**Pull request merged**
