### PR TITLE
tiny-count: anchored selector changes, user experience improvements for overlap selectors

### LINKED ISSUE #281: tiny-count: changes to anchored selector semantics, and user experience improvements for overlap selectors
Now that tiny-count supports shift parameters for overlap selectors, we are changing the semantics of `5' anchored`, `3' anchored`, and `anchored` overlap selectors to require nesting of the non-anchored end of the alignment within the feature's interval. 

Shift parameters can produce illegal feature intervals. Currently we simply drop these feature-rule pairs without notifying the user. This behavior needs to be further developed so that the user is notified of the specific matches that were dropped and why.

To further improve the user experience with overlap selectors, "full" will be renamed to "nested", and the overlap column in the Features Sheet will support wildcard keywords (`any`, `all`, `*`, and an empty cell) so that users don't have to specify "partial" in fully permissive rules

### PR DESCRIPTION
**Pull request by AlexTate**
### Anchored overlap selectors
The semantics of `5' anchored`, `3' anchored`, and `anchored` overlap selectors have been changed to require nesting of the non-anchored end of the alignment within the feature's interval. This, along with the recently introduced overlap shift parameters, furthers our goal of adding support for the quantification of isomiRs

### Invalid shifted interval warnings
The user is now notified if an invalid feature interval is produced as a result of an overlap shift parameter. These feature-rule pairs are omitted from selection so it's important for the user to be aware. The notice includes the specific feature IDs and their matched rule + selector definition, and these matches are organized into descriptive sections by violation type (null, inverted, or negative start).

### User experience improvements
- The "full" overlap selector has been renamed to "nested" to be more descriptive
- The Overlap column of the Features Sheet now supports wildcard keywords (`any`, `all`, `*`, and an empty cell) to make it more consistent with the other columns. This is functionally equivalent to specifying "partial"

### Documentation diagram changes
- Overlap selector descriptions and figures have been updated and improved. Note that documentation updates for shift parameters and counting by sequence will be added in a followup PR once these features are finalized
- An additional rule has been added to the selection diagram to hint at support for isomiR quantification
- Text and line elements that were red have been changed to magenta as an initial step in supporting colorblind users. Text and line elements that were previously magenta are now light blue.

Closes #281

### CODE REVIEW

**Comment by AlexTate** [comment]
### Changes to overlap selector caching
Expanded cache scope. Previously the cache was only used per subinterval per feature. Now it reaches across features and GFF files too. The cache is used to reduce memory footprint by preventing duplicate instances from being created for the same interval and overlap selector type.

### More memory efficient overlap selector instances
The Interval*Match classes only ever need to hold start and end coordinates. They don't need to support dynamic attribute creation, which Python classes support but at a cost. After removing this feature the memory footprint of overlap selectors was reduced by ~75% with my local test config. In worst case scenarios instances of these classes can be very, very numerous.

### Aesthetic documentation changes
The color and transparency of larger shapes in the selection diagram has been slightly modified to make it easier on the eyes with GitHub's dark theme.

**Comment by taimontgomery** [comment]
images/tiny-count_selection.png
1.  Change Full to Nested
2.  Change miRNA rule to Overlap=5'Anchored, 0, 5
3.  Change isomiR rule to Hierarchy=3

**Comment by AlexTate** [comment]
> 1. Change Full to Nested

Thanks for catching that, missed that one

> 2. Change miRNA rule to Overlap=5'Anchored, 0, 5
> 3. Change isomiR rule to Hierarchy=3

Ok, I've added the new ruleset to the diagram

Selection_Diagram_1 9 1

**Comment by taimontgomery** [comment]
Tested rigorously with ram1 data.  Minimal testing with zswim and Lib303 data. All tests passed.

**Pull request merged**
